### ISSUE TITLE
Main page with search bar

### ISSUE THREAD

**Issue by MemduhG** [woolwood/vortaro#1]
Main page to look up words, show the matching entries in some reasonable format. Doesn't have to be asynchronous for now, but asynchronous suggestions while typing in the search bar would be a nice to have.

**Comment by MemduhG** [comment]
I would be fine for now if it was just a few fields, even as simple as the headword itself and the text of each associated `anlam` entry.

**Comment by woolwood** [comment]
More work has to be done on presenting the data but the basis of this issue is covered.
